---
- name: Common Tasks
  hosts: all
  become: true
  roles:
    - common

- name: Master Tasks
  hosts: master
  become: true
  roles:
    - master

- name: Worker Tasks
  hosts: worker
  become: true
  roles:
    - worker

- name: Run setup commands on control node
  hosts: localhost
  connection: local
  become: true
  roles:
    - local