- name: Fetch join_command.txt Control Node
  copy:
    src:  /tmp/join_command.txt
    dest: /tmp/
  when: ansible_facts['os_family'] == 'RedHat'
  
- name: Read join_command.txt
  command: cat /tmp/join_command.txt
  register: join_command_output
  changed_when: false
  when: ansible_facts['os_family'] == 'RedHat'
  
- name: Execute join command
  shell: "{{ join_command_output.stdout }}"
  args:
    executable: /bin/bash
  changed_when: false
  when: ansible_facts['os_family'] == 'RedHat'
  